import { Bakery } from '@/types'

export const MOCK_BAKERIES: Record<string, Bakery> = {
  'bakery-la-esperanza': {
    id: 'bakery-la-esperanza',
    name: 'Panadería La Esperanza',
    ownerId: 'p1',
    address: 'Cra 7 #45-23, Chapinero',
    lat: 4.6486,
    lng: -74.0625,
    rating: 4.7,
    reviewsCount: 142,
    isCertified: true,
    availableProducts: ['chocoramo', 'arequipe', 'blanco'],
    isActive: true,
  },
  'bakery-el-trigal': {
    id: 'bakery-el-trigal',
    name: 'Panadería El Trigal',
    ownerId: 'p2',
    address: 'Calle 85 #15-30, Zona Rosa',
    lat: 4.6732,
    lng: -74.0521,
    rating: 4.8,
    reviewsCount: 203,
    isCertified: true,
    availableProducts: ['chocoramo', 'blanco'],
    isActive: true,
  },
  'bakery-don-pan': {
    id: 'bakery-don-pan',
    name: 'Panadería Don Pan',
    address: 'Calle 53 #13-45, Teusaquillo',
    lat: 4.663,
    lng: -74.0657,
    rating: 4.5,
    reviewsCount: 87,
    isCertified: true,
    availableProducts: ['chocoramo', 'arequipe'],
    isActive: true,
  },
  'bakery-pan-casero': {
    id: 'bakery-pan-casero',
    name: 'Pan Casero Bogotá',
    address: 'Carrera 11 #86-25, Usaquén',
    lat: 4.7211,
    lng: -74.0301,
    rating: 4.6,
    reviewsCount: 156,
    isCertified: false,
    availableProducts: ['arequipe', 'blanco'],
    isActive: true,
  },
  'bakery-tradicion': {
    id: 'bakery-tradicion',
    name: 'Panadería Tradición',
    address: 'Cra 19 #51-60, La Candelaria',
    lat: 4.5929,
    lng: -74.0755,
    rating: 4.4,
    reviewsCount: 98,
    isCertified: true,
    availableProducts: ['chocoramo', 'blanco'],
    isActive: true,
  },
  'bakery-sabor-fresco': {
    id: 'bakery-sabor-fresco',
    name: 'Sabor Fresco',
    address: 'Calle 127 #7-45, Barrio Niza',
    lat: 4.7548,
    lng: -74.0356,
    rating: 4.9,
    reviewsCount: 215,
    isCertified: true,
    availableProducts: ['chocoramo', 'arequipe', 'blanco'],
    isActive: true,
  },
}
