import { Product } from '@/types'

export const MOCK_PRODUCTS: Record<string, Product> = {
  'torta-mixta': {
    id: 'torta-mixta',
    name: 'Torta Mixta',
    price: 12500,
    description: 'Torta esponjosa con frutas y crema',
    image: '/torta-mixta.jpeg',
  },
  'porcion-torta-mixta': {
    id: 'porcion-torta-mixta',
    name: 'Porción Torta Mixta',
    price: 4300,
    description: 'Generosa porción de torta mixta',
    image: '/torta-mixta.jpeg',
  },
  'torta-arequipe': {
    id: 'torta-arequipe',
    name: 'Torta Arequipeños',
    price: 12500,
    description: 'Deliciosa torta con relleno de arequipe y nueces',
    image: '/torta-arequipe.jpeg',
  },
  'porcion-torta-arequipe': {
    id: 'porcion-torta-arequipe',
    name: 'Porción Torta Arequipeños',
    price: 4300,
    description: 'Generosa porción de torta arequipeños',
    image: '/torta-arequipe.jpeg',
  },
  'torta-chocolate-blanco': {
    id: 'torta-chocolate-blanco',
    name: 'Torta Cubierta Chocolate Blanco',
    price: 12500,
    description: 'Torta con cobertura de chocolate blanco premium',
    image: '/torta-chocolate-blanco.jpeg',
  },
  'porcion-torta-chocolate-blanco': {
    id: 'porcion-torta-chocolate-blanco',
    name: 'Porción Torta Chocolate Blanco',
    price: 4300,
    description: 'Generosa porción de torta con chocolate blanco',
    image: '/torta-chocolate-blanco.jpeg',
  },
  'torta-chocolate-negro': {
    id: 'torta-chocolate-negro',
    name: 'Torta Cubierta Chocolate Negro',
    price: 12500,
    description: 'Torta con cobertura de chocolate negro intenso',
    image: '/torta-chocolate-negro.jpeg',
  },
  'porcion-torta-chocolate-negro': {
    id: 'porcion-torta-chocolate-negro',
    name: 'Porción Torta Chocolate Negro',
    price: 4300,
    description: 'Generosa porción de torta con chocolate negro',
    image: '/torta-chocolate-negro.jpeg',
  },
  'chocoramo-fresh': {
    id: 'chocoramo-fresh',
    name: 'Chocoramo Fresh',
    price: 3500,
    description: 'Chocoramo recién horneado, crujiente y delicioso',
    image: '/chocoramo-fresh.jpeg',
  },
  'bites-ramo-4': {
    id: 'bites-ramo-4',
    name: 'Bites Ramo x4',
    price: 8000,
    description: 'Caja de 4 bites de chocolate, perfectos para compartir',
    image: '/bites-ramo.jpeg',
  },
  'bites-ramo-6': {
    id: 'bites-ramo-6',
    name: 'Bites Ramo x6',
    price: 11000,
    description: 'Caja de 6 bites de chocolate, ideal para la familia',
    image: '/bites-ramo.jpeg',
  },
  'bites-ramo-8': {
    id: 'bites-ramo-8',
    name: 'Bites Ramo x8',
    price: 14000,
    description: 'Caja de 8 bites de chocolate, perfecta para eventos',
    image: '/bites-ramo.jpeg',
  },
  'bites-ramo-10': {
    id: 'bites-ramo-10',
    name: 'Bites Ramo x10',
    price: 17000,
    description: 'Caja de 10 bites de chocolate, para verdaderos amantes',
    image: '/bites-ramo.jpeg',
  },
}
